server:
  port: 3000

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/project
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true